name: Walking Steel
favicon: null
layout_spectrum: 0.50337
typography_spectrum: 0.68654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#6b6c6e'
    - '#262627'
    - '#752908'
    - '#8f533c'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
